logins:
    - name: codeberg.org
      url: https://codeberg.org
      token: 0d466029450a464481a1bf464d48ba11fb8fe4a2
      default: false
      ssh_host: codeberg.org
      ssh_key: ""
      insecure: false
      ssh_certificate_principal: ""
      ssh_agent: false
      ssh_key_agent_pub: ""
      version_check: true
      user: funkybooboo
      created: 1766367813
      refresh_token: ""
      token_expiry: 0
preferences:
    editor: false
    flag_defaults:
        remote: ""
